# Generated by Django 5.2 on 2025-04-19 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='social',
            new_name='socialBonus',
        ),
    ]
