# Generated by Django 5.2 on 2025-04-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_praise_tip'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('total_score', models.IntegerField()),
                ('include_in_leaderboard', models.BooleanField(default=False)),
            ],
        ),
    ]
