# Generated by Django 5.2 on 2025-04-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_userscore_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscore',
            name='include_in_leaderboard',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
