# Generated by Django 5.2 on 2025-04-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_userscore_include_in_leaderboard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='category',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(default='Category', max_length=50),
            preserve_default=False,
        ),
    ]
