# Generated by Django 5.2 on 2025-04-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_option_category_question_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Praise',
        ),
        migrations.DeleteModel(
            name='Tip',
        ),
        migrations.RemoveField(
            model_name='option',
            name='socialBonus',
        ),
        migrations.AddField(
            model_name='option',
            name='praise',
            field=models.CharField(default='text', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option',
            name='tip',
            field=models.CharField(default='text', max_length=300),
            preserve_default=False,
        ),
    ]
