# Generated by Django 5.2 on 2025-04-29 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_delete_praise_delete_tip_remove_option_socialbonus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='praise',
            new_name='extra',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='tip',
            new_name='improvement',
        ),
    ]
