# Generated by Django 5.2 on 2025-04-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_rename_praise_option_extra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='extra',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='improvement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
